In [7]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

ModuleNotFoundError: No module named 'pandas'

In [3]:
dataset1 = pd.read_csv("../data/dataset1.csv")
dataset2 = pd.read_csv("../data/dataset2.csv")

In [4]:
print(dataset1.shape)
print(dataset2.shape)

(29999, 23)
(29999, 35)

In [5]:
dataset1.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,post_hour,day_of_week,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,6,Saturday,194,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,15,Friday,449,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,16,Thursday,114,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,3,Thursday,91,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,9,Friday,154,8,5,21,5350,8503,0.0221,155,112,9,low

In [6]:
dataset2.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,post_hour,day_of_week,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,weekend_flag,month,week_of_year,quarter,total_posts_count,avg_likes_last_10_posts,avg_comments_last_10_posts,avg_engagement_last_10_posts,days_since_last_post,hours_since_last_post,posting_frequency_per_week,viral_flag
0,IG0008958,1,brand,9461,carousel,Lifestyle,External,0,2024-11-19 05:00:00,2024-11-19,5,Tuesday,83,1,4,10,1898,2589,0.0379,468,145,10,medium,0,11,47,4,1462,NaN,NaN,NaN,NaN,NaN,28.038356,0
1,IG0005710,1,creator,9461,carousel,Beauty,Profile,0,2024-11-19 07:00:00,2024-11-19,7,Tuesday,96,2,3,11,1856,2895,0.0387,89,107,7,medium,0,11,47,4,1462,83.000000,1.00,0.037900,0.0,2.0,28.038356,0
2,IG0006615,1,creator,9461,image,Technology,Explore,1,2024-11-19 07:00:00,2024-11-19,7,Tuesday,350,6,7,38,5585,7532,0.0532,804,112,10,viral,0,11,47,4,1462,89.500000,1.50,0.038300,0.0,0.0,28.038356,0
3,IG0022743,1,creator,9461,image,Lifestyle,Home Feed,0,2024-11-19 10:00:00,2024-11-19,10,Tuesday,118,4,6,16,1555,2130,0.0676,371,128,9,viral,0,11,47,4,1462,176.333333,3.00,0.043267,0.0,3.0,28.038356,0
4,IG0016262,1,brand,9461,reel,Lifestyle,External,0,2024-11-19 12:00:00,2024-11-19,12,Tuesday,120,4,5,17,9173,14481,0.0101,866,117,3,low,0,11,47,4,1462,161.750000,3.25,0.049350,0.0,2.0,28.038356,0

In [7]:
dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  str
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  str
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  str
 5   content_category          29999 non-null  str
 6   traffic_source            29999 non-null  str
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  str
 9   post_date                 29999 non-null  str
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  str
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  str
dtypes: float64(1), int64(13), str(9)
memory usage: 5.3 MB

In [8]:
dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   post_id                       29999 non-null  str
 1   account_id                    29999 non-null  int64
 2   account_type                  29999 non-null  str
 3   follower_count                29999 non-null  int64
 4   media_type                    29999 non-null  str
 5   content_category              29999 non-null  str
 6   traffic_source                29999 non-null  str
 7   has_call_to_action            29999 non-null  int64
 8   post_datetime                 29999 non-null  str
 9   post_date                     29999 non-null  str
 10  post_hour                     29999 non-null  int64
 11  day_of_week                   29999 non-null  str
 12  likes                         29999 non-null  int64
 13  comments                      29999 non-null  int64
 14  shares                        29999 non-null  int64
 15  saves                         29999 non-null  int64
 16  reach                         29999 non-null  int64
 17  impressions                   29999 non-null  int64
 18  engagement_rate               29999 non-null  float64
 19  followers_gained              29999 non-null  int64
 20  caption_length                29999 non-null  int64
 21  hashtags_count                29999 non-null  int64
 22  performance_bucket_label      29999 non-null  str
 23  weekend_flag                  29999 non-null  int64
 24  month                         29999 non-null  int64
 25  week_of_year                  29999 non-null  int64
 26  quarter                       29999 non-null  int64
 27  total_posts_count             29999 non-null  int64
 28  avg_likes_last_10_posts       29979 non-null  float64
 29  avg_comments_last_10_posts    29979 non-null  float64
 30  avg_engagement_last_10_posts  29979 non-null  float64
 31  days_since_last_post          29979 non-null  float64
 32  hours_since_last_post         29979 non-null  float64
 33  posting_frequency_per_week    29999 non-null  float64
 34  viral_flag                    29999 non-null  int64
dtypes: float64(7), int64(19), str(9)
memory usage: 8.0 MB

In [9]:
dataset1.describe(include="all")

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,post_hour,day_of_week,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
count,29999,29999.000000,29999,29999.000000,29999,29999,29999,29999.000000,29999,29999,29999.000000,29999,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999
unique,29999,NaN,2,NaN,3,10,6,NaN,8475,366,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
top,IG0000001,NaN,creator,NaN,image,Photography,Home Feed,NaN,2025-02-06 14:00:00,2025-02-26,NaN,Thursday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,viral
freq,1,NaN,20944,NaN,11927,3035,5069,NaN,13,110,NaN,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500
mean,NaN,10.567819,NaN,10278.305477,NaN,NaN,NaN,0.348778,NaN,NaN,11.499417,NaN,287.653588,8.521917,14.426614,42.517284,6272.475449,8466.952498,0.042107,502.152805,120.081169,7.987933,NaN
std,NaN,5.763952,NaN,6691.862669,NaN,NaN,NaN,0.476592,NaN,NaN,6.900587,NaN,317.647682,10.116505,16.420899,47.808844,4985.877059,6825.900355,0.024095,290.364038,11.009108,2.828130,NaN
min,NaN,1.000000,NaN,3083.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,268.000000,327.000000,0.000000,0.000000,70.000000,0.000000,NaN
25%,NaN,6.000000,NaN,5824.000000,NaN,NaN,NaN,0.000000,NaN,NaN,6.000000,NaN,104.000000,3.000000,5.000000,15.000000,3058.000000,4102.000000,0.024000,251.000000,113.000000,6.000000,NaN
50%,NaN,11.000000,NaN,9044.000000,NaN,NaN,NaN,0.000000,NaN,NaN,12.000000,NaN,199.000000,6.000000,10.000000,29.000000,4913.000000,6595.000000,0.040600,501.000000,120.000000,8.000000,NaN
75%,NaN,16.000000,NaN,10739.000000,NaN,NaN,NaN,1.000000,NaN,NaN,17.000000,NaN,363.000000,11.000000,19.000000,54.000000,7863.000000,10620.500000,0.057000,755.000000,127.000000,10.000000,NaN
max,NaN,20.000000,NaN,31095.000000,NaN,NaN,NaN,1.000000,NaN,NaN,23.000000,NaN,10632.000000,339.000000,516.000000,1542.000000,73339.000000,105203.000000,0.271000,1000.000000,166.000000,21.000000,NaN

In [10]:
dataset2.describe(include="all")

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,post_hour,day_of_week,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,weekend_flag,month,week_of_year,quarter,total_posts_count,avg_likes_last_10_posts,avg_comments_last_10_posts,avg_engagement_last_10_posts,days_since_last_post,hours_since_last_post,posting_frequency_per_week,viral_flag
count,29999,29999.000000,29999,29999.000000,29999,29999,29999,29999.000000,29999,29999,29999.000000,29999,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29979.000000,29979.000000,29979.000000,29979.000000,29979.000000,29999.000000,29999.000000
unique,29999,NaN,2,NaN,3,10,6,NaN,8475,366,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,IG0008958,NaN,creator,NaN,image,Photography,Home Feed,NaN,2025-02-06 14:00:00,2025-02-26,NaN,Tuesday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,viral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,20944,NaN,11927,3035,5069,NaN,13,110,NaN,4351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,10.567819,NaN,10278.305477,NaN,NaN,NaN,0.348778,NaN,NaN,11.499417,NaN,287.653588,8.521917,14.426614,42.517284,6272.475449,8466.952498,0.042107,502.152805,120.081169,7.987933,NaN,0.281976,6.514050,26.515851,2.508217,1501.716024,287.573402,8.520445,0.042101,0.019580,5.852263,28.800033,0.100603
std,NaN,5.763952,NaN,6691.862669,NaN,NaN,NaN,0.476592,NaN,NaN,6.900587,NaN,317.647682,10.116505,16.420899,47.808844,4985.877059,6825.900355,0.024095,290.364038,11.009108,2.828130,NaN,0.449969,3.457695,15.061363,1.119616,51.756794,102.402886,3.218707,0.007641,0.140468,5.918618,0.992596,0.300808
min,NaN,1.000000,NaN,3083.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,268.000000,327.000000,0.000000,0.000000,70.000000,0.000000,NaN,0.000000,1.000000,1.000000,1.000000,1392.000000,41.000000,0.000000,0.011450,0.000000,0.000000,26.695890,0.000000
25%,NaN,6.000000,NaN,5824.000000,NaN,NaN,NaN,0.000000,NaN,NaN,6.000000,NaN,104.000000,3.000000,5.000000,15.000000,3058.000000,4102.000000,0.024000,251.000000,113.000000,6.000000,NaN,0.000000,4.000000,14.000000,2.000000,1472.000000,218.600000,6.300000,0.036960,0.000000,2.000000,28.230137,0.000000
50%,NaN,11.000000,NaN,9044.000000,NaN,NaN,NaN,0.000000,NaN,NaN,12.000000,NaN,199.000000,6.000000,10.000000,29.000000,4913.000000,6595.000000,0.040600,501.000000,120.000000,8.000000,NaN,0.000000,7.000000,26.000000,3.000000,1494.000000,272.100000,8.000000,0.041530,0.000000,4.000000,28.652055,0.000000
75%,NaN,16.000000,NaN,10739.000000,NaN,NaN,NaN,1.000000,NaN,NaN,17.000000,NaN,363.000000,11.000000,19.000000,54.000000,7863.000000,10620.500000,0.057000,755.000000,127.000000,10.000000,NaN,1.000000,10.000000,40.000000,4.000000,1530.000000,335.800000,10.100000,0.046540,0.000000,8.000000,29.342466,0.000000
max,NaN,20.000000,NaN,31095.000000,NaN,NaN,NaN,1.000000,NaN,NaN,23.000000,NaN,10632.000000,339.000000,516.000000,1542.000000,73339.000000,105203.000000,0.271000,1000.000000,166.000000,21.000000,NaN,1.000000,12.000000,52.000000,4.000000,1599.000000,1578.000000,43.100000,0.100500,2.000000,63.000000,30.665753,1.000000

In [11]:
dataset1.isnull().sum()

post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [12]:
dataset2.isnull().sum()

post_id                          0
account_id                       0
account_type                     0
follower_count                   0
media_type                       0
content_category                 0
traffic_source                   0
has_call_to_action               0
post_datetime                    0
post_date                        0
post_hour                        0
day_of_week                      0
likes                            0
comments                         0
shares                           0
saves                            0
reach                            0
impressions                      0
engagement_rate                  0
followers_gained                 0
caption_length                   0
hashtags_count                   0
performance_bucket_label         0
weekend_flag                     0
month                            0
week_of_year                     0
quarter                          0
total_posts_count                0
avg_likes_last_10_posts         20
avg_comments_last_10_posts      20
avg_engagement_last_10_posts    20
days_since_last_post            20
hours_since_last_post           20
posting_frequency_per_week       0
viral_flag                       0
dtype: int64

In [13]:
dataset1.duplicated().sum()

np.int64(0)

In [14]:
dataset2.duplicated().sum()

np.int64(0)

In [15]:
print(dataset1.columns.tolist())

['post_id', 'account_id', 'account_type', 'follower_count', 'media_type', 'content_category', 'traffic_source', 'has_call_to_action', 'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 'engagement_rate', 'followers_gained', 'caption_length', 'hashtags_count', 'performance_bucket_label']

In [16]:
print(dataset2.columns.tolist())

['post_id', 'account_id', 'account_type', 'follower_count', 'media_type', 'content_category', 'traffic_source', 'has_call_to_action', 'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 'engagement_rate', 'followers_gained', 'caption_length', 'hashtags_count', 'performance_bucket_label', 'weekend_flag', 'month', 'week_of_year', 'quarter', 'total_posts_count', 'avg_likes_last_10_posts', 'avg_comments_last_10_posts', 'avg_engagement_last_10_posts', 'days_since_last_post', 'hours_since_last_post', 'posting_frequency_per_week', 'viral_flag']

In [6]:
import pandas as pd

df = pd.read_csv("backend/ml/data/dataset2.csv")

print(df["viral_flag"].value_counts())
print(df["viral_flag"].value_counts(normalize=True))

ModuleNotFoundError: No module named 'pandas'